import type { PolicySeed } from "@/lib/policy/fixture-repository";
import type { BenefitLineCreateInput } from "@/lib/policy/types";
import { seedTerritoryEligibility } from "@/lib/policy/eligibility-seed";
import { TERRITORY_FIXTURES } from "@/lib/territory/fixtures";

const SEED = new Date("2025-12-01T00:00:00.000Z");
const EXPIRY = new Date("2026-11-30T00:00:00.000Z");

const FIXED_SUM_ESSENTIAL_BENEFITS: BenefitLineCreateInput[] = [
  { benefitType: "DEATH", amountBasis: "LUMP_SUM", fixedAmount: 50_000 },
  { benefitType: "PTD", amountBasis: "LUMP_SUM", fixedAmount: 150_000 },
  {
    benefitType: "TTD",
    amountBasis: "PERIODIC",
    fixedAmount: 2_500,
    waitingPeriodDays: 7,
    maxBenefitWeeks: 104,
  },
  { benefitType: "MEDICAL", amountBasis: "LUMP_SUM", fixedAmount: 700_000 },
  { benefitType: "EVACUATION", amountBasis: "LUMP_SUM", fixedAmount: 500_000 },
];

const FIXED_SUM_PREMIUM_BENEFITS: BenefitLineCreateInput[] = [
  { benefitType: "DEATH", amountBasis: "LUMP_SUM", fixedAmount: 150_000 },
  { benefitType: "PTD", amountBasis: "LUMP_SUM", fixedAmount: 150_000 },
  {
    benefitType: "TTD",
    amountBasis: "PERIODIC",
    fixedAmount: 2_500,
    waitingPeriodDays: 7,
    maxBenefitWeeks: 104,
  },
  { benefitType: "MEDICAL", amountBasis: "LUMP_SUM", fixedAmount: 700_000 },
  { benefitType: "EVACUATION", amountBasis: "LUMP_SUM", fixedAmount: 500_000 },
];

/**
 * GRAA Fixed Sum (GPA) on-risk schedule + African Parks (demo) Earnings-Based
 * (Stated Benefits) schedule. Placeholder rates only for AP — real schedule loads later.
 */
export const POLICY_FIXTURES: PolicySeed = {
  paymentTerms: [
    {
      id: "pay-graa-monthly",
      clientId: "client-graa",
      frequency: "MONTHLY_BY_NUMBERS",
      depositMinPremium: null,
      adjustmentCadenceMonths: null,
      aggregateIsClientFund: true,
      createdAt: SEED,
      updatedAt: SEED,
    },
    {
      id: "pay-aparks-monthly",
      clientId: "client-aparks",
      frequency: "MONTHLY_BY_NUMBERS",
      depositMinPremium: null,
      adjustmentCadenceMonths: 6,
      aggregateIsClientFund: false,
      createdAt: SEED,
      updatedAt: SEED,
    },
  ],
  policies: [
    {
      id: "policy-graa-2025-26",
      clientId: "client-graa",
      policyYear: "2025-2026",
      inceptionDate: SEED,
      expiryDate: EXPIRY,
      status: "ON_RISK",
      benefitScale: "FIXED_SUM",
      paymentTermsId: "pay-graa-monthly",
      underwriterUserId: "user-insurer",
      brokerOrganisationId: "broker-lombard",
      createdAt: SEED,
      updatedAt: SEED,
    },
    {
      id: "policy-aparks-2025-26",
      clientId: "client-aparks",
      policyYear: "2025-2026",
      inceptionDate: SEED,
      expiryDate: EXPIRY,
      status: "ON_RISK",
      benefitScale: "EARNINGS_BASED",
      paymentTermsId: "pay-aparks-monthly",
      underwriterUserId: "user-insurer",
      brokerOrganisationId: "broker-lombard",
      createdAt: SEED,
      updatedAt: SEED,
    },
  ],
  coverCategories: [
    {
      id: "cat-graa-essential",
      policyId: "policy-graa-2025-26",
      clientId: "client-graa",
      categoryLabel: "Category 1 — Essential Cover",
      planType: "ESSENTIAL",
      basisOfCover: "TWENTY_FOUR_HOUR",
      basisOfCoverOther: null,
      declaredInsuredCount: 6503,
      declaredAnnualWageRoll: null,
      premiumAmount: 24.06,
      premiumBasis: "PER_PERSON_PER_MONTH",
      premiumIncludesVat: true,
      aggregateAmount: 35,
      aggregateBasis: "PER_PERSON_PER_MONTH",
      aggregateExcludesVat: true,
      sortOrder: 0,
      createdAt: SEED,
      updatedAt: SEED,
    },
    {
      id: "cat-graa-premium",
      policyId: "policy-graa-2025-26",
      clientId: "client-graa",
      categoryLabel: "Category 3 — Premium Cover",
      planType: "PREMIUM",
      basisOfCover: "TWENTY_FOUR_HOUR",
      basisOfCoverOther: null,
      declaredInsuredCount: 14,
      declaredAnnualWageRoll: null,
      premiumAmount: 77.44,
      premiumBasis: "PER_PERSON_PER_MONTH",
      premiumIncludesVat: true,
      aggregateAmount: 112.44,
      aggregateBasis: "PER_PERSON_PER_MONTH",
      aggregateExcludesVat: true,
      sortOrder: 1,
      createdAt: SEED,
      updatedAt: SEED,
    },
    {
      id: "cat-aparks-staff",
      policyId: "policy-aparks-2025-26",
      clientId: "client-aparks",
      categoryLabel: "All Staff — Stated Benefits (demo)",
      planType: "PREMIUM",
      basisOfCover: "TWENTY_FOUR_HOUR",
      basisOfCoverOther: null,
      declaredInsuredCount: 120,
      declaredAnnualWageRoll: 18_000_000,
      premiumAmount: 1.2,
      premiumBasis: "PERCENT_OF_WAGE_ROLL",
      premiumIncludesVat: true,
      aggregateAmount: 0.8,
      aggregateBasis: "PERCENT_OF_WAGE_ROLL",
      aggregateExcludesVat: true,
      sortOrder: 0,
      createdAt: SEED,
      updatedAt: SEED,
    },
  ],
  benefitLines: [
    ...FIXED_SUM_ESSENTIAL_BENEFITS.map((b, i) => ({
      id: `ben-graa-ess-${i}`,
      coverCategoryId: "cat-graa-essential",
      clientId: "client-graa",
      benefitType: b.benefitType,
      amountBasis: b.amountBasis,
      waitingPeriodDays: b.waitingPeriodDays ?? null,
      maxBenefitWeeks: b.maxBenefitWeeks ?? null,
      notes: null,
      fixedAmount: b.fixedAmount ?? null,
      earningsMultiple: null,
      percentOfEarnings: null,
      maxAmountCap: null,
      createdAt: SEED,
      updatedAt: SEED,
    })),
    ...FIXED_SUM_PREMIUM_BENEFITS.map((b, i) => ({
      id: `ben-graa-prem-${i}`,
      coverCategoryId: "cat-graa-premium",
      clientId: "client-graa",
      benefitType: b.benefitType,
      amountBasis: b.amountBasis,
      waitingPeriodDays: b.waitingPeriodDays ?? null,
      maxBenefitWeeks: b.maxBenefitWeeks ?? null,
      notes: null,
      fixedAmount: b.fixedAmount ?? null,
      earningsMultiple: null,
      percentOfEarnings: null,
      maxAmountCap: null,
      createdAt: SEED,
      updatedAt: SEED,
    })),
    {
      id: "ben-aparks-death",
      coverCategoryId: "cat-aparks-staff",
      clientId: "client-aparks",
      benefitType: "DEATH",
      amountBasis: "LUMP_SUM",
      waitingPeriodDays: null,
      maxBenefitWeeks: null,
      notes: "Placeholder — replace with real African Parks schedule",
      fixedAmount: null,
      earningsMultiple: 3,
      percentOfEarnings: null,
      maxAmountCap: 2_000_000,
      createdAt: SEED,
      updatedAt: SEED,
    },
    {
      id: "ben-aparks-ptd",
      coverCategoryId: "cat-aparks-staff",
      clientId: "client-aparks",
      benefitType: "PTD",
      amountBasis: "LUMP_SUM",
      waitingPeriodDays: null,
      maxBenefitWeeks: null,
      notes: null,
      fixedAmount: null,
      earningsMultiple: 3,
      percentOfEarnings: null,
      maxAmountCap: 2_000_000,
      createdAt: SEED,
      updatedAt: SEED,
    },
    {
      id: "ben-aparks-ttd",
      coverCategoryId: "cat-aparks-staff",
      clientId: "client-aparks",
      benefitType: "TTD",
      amountBasis: "PERIODIC",
      waitingPeriodDays: 7,
      maxBenefitWeeks: 104,
      notes: null,
      fixedAmount: null,
      earningsMultiple: null,
      percentOfEarnings: 100,
      maxAmountCap: null,
      createdAt: SEED,
      updatedAt: SEED,
    },
    {
      id: "ben-aparks-med",
      coverCategoryId: "cat-aparks-staff",
      clientId: "client-aparks",
      benefitType: "MEDICAL",
      amountBasis: "LUMP_SUM",
      waitingPeriodDays: null,
      maxBenefitWeeks: null,
      notes: null,
      fixedAmount: 100_000,
      earningsMultiple: null,
      percentOfEarnings: null,
      maxAmountCap: null,
      createdAt: SEED,
      updatedAt: SEED,
    },
    {
      id: "ben-aparks-evac",
      coverCategoryId: "cat-aparks-staff",
      clientId: "client-aparks",
      benefitType: "EVACUATION",
      amountBasis: "LUMP_SUM",
      waitingPeriodDays: null,
      maxBenefitWeeks: null,
      notes: null,
      fixedAmount: 250_000,
      earningsMultiple: null,
      percentOfEarnings: null,
      maxAmountCap: null,
      createdAt: SEED,
      updatedAt: SEED,
    },
  ],
  riskMixPolicies: [
    {
      id: "mix-graa",
      clientId: "client-graa",
      targetLowMedPct: 85,
      targetHighPct: 10,
      targetVeryHighPct: 5,
      tolerancePct: 2,
      effectiveFrom: SEED,
      effectiveTo: null,
      createdAt: SEED,
      updatedAt: SEED,
    },
    {
      id: "mix-aparks",
      clientId: "client-aparks",
      targetLowMedPct: 80,
      targetHighPct: 15,
      targetVeryHighPct: 5,
      tolerancePct: 3,
      effectiveFrom: SEED,
      effectiveTo: null,
      createdAt: SEED,
      updatedAt: SEED,
    },
  ],
  territoryEligibilities: [
    ...seedTerritoryEligibility({
      clientId: "client-graa",
      categories: [
        { id: "cat-graa-essential", planType: "ESSENTIAL" },
        { id: "cat-graa-premium", planType: "PREMIUM" },
      ],
      territories: TERRITORY_FIXTURES.map((t) => ({
        id: t.id,
        benefitOptions: t.benefitOptions,
      })),
    }).map((row, i) => ({
      id: `elig-graa-${String(i)}`,
      territoryId: row.territoryId,
      coverCategoryId: row.coverCategoryId,
      clientId: row.clientId,
      createdAt: SEED,
    })),
    ...seedTerritoryEligibility({
      clientId: "client-aparks",
      categories: [{ id: "cat-aparks-staff", planType: "PREMIUM" }],
      territories: TERRITORY_FIXTURES.map((t) => ({
        id: t.id,
        benefitOptions: t.benefitOptions,
      })),
    }).map((row, i) => ({
      id: `elig-aparks-${String(i)}`,
      territoryId: row.territoryId,
      coverCategoryId: row.coverCategoryId,
      clientId: row.clientId,
      createdAt: SEED,
    })),
  ],
};
