import type { OrgLocationSeed } from "@/lib/org-location/fixture-repository";

const SEED_DATE = new Date("2026-01-01T00:00:00.000Z");

/**
 * Demo member orgs and locations for GRAA. Placeholder names only — never real
 * reserve/park operators or personal information (POPIA).
 * coverCategoryId wired to GRAA on-risk schedule categories.
 */
export const ORG_LOCATION_FIXTURES: OrgLocationSeed = {
  memberOrganisations: [
    {
      id: "member-demo-north",
      clientId: "client-graa",
      name: "Northern Reserve Operator (demo)",
      status: "ACTIVE",
      defaultPlanType: "ESSENTIAL",
      riskMgmtPlanOnFile: true,
      crisisMgmtPlanOnFile: true,
      fullUnderwritingApproved: false,
      contactName: "Demo Contact North",
      contactEmail: "north-ops@example.com",
      contactPhone: null,
      operationsNote: "Demo reserve operator for GRAA fixtures",
      lastCensusAcceptedAt: new Date("2025-11-15T00:00:00.000Z"),
      createdAt: SEED_DATE,
      updatedAt: SEED_DATE,
    },
    {
      id: "member-demo-south",
      clientId: "client-graa",
      name: "Southern Park Operator (demo)",
      status: "UNDER_REVIEW",
      defaultPlanType: "PREMIUM",
      riskMgmtPlanOnFile: false,
      crisisMgmtPlanOnFile: false,
      fullUnderwritingApproved: true,
      contactName: "Demo Contact South",
      contactEmail: "south-ops@example.com",
      contactPhone: null,
      operationsNote: null,
      lastCensusAcceptedAt: null,
      createdAt: SEED_DATE,
      updatedAt: SEED_DATE,
    },
  ],
  locations: [
    {
      id: "loc-demo-zaf",
      clientId: "client-graa",
      memberOrganisationId: "member-demo-north",
      territoryId: "terr-zaf",
      siteName: "Demo reserve — Low risk",
      headcount: 47,
      assignedPlanType: "ESSENTIAL",
      coverCategoryId: "cat-graa-essential",
      createdAt: SEED_DATE,
      updatedAt: SEED_DATE,
    },
    {
      id: "loc-demo-ken",
      clientId: "client-graa",
      memberOrganisationId: "member-demo-south",
      territoryId: "terr-ken",
      siteName: "Demo park — Kenya",
      headcount: 16,
      assignedPlanType: "PREMIUM",
      coverCategoryId: "cat-graa-premium",
      createdAt: SEED_DATE,
      updatedAt: SEED_DATE,
    },
  ],
  endorsements: [
    {
      id: "end-demo-zaf-baseline",
      clientId: "client-graa",
      organisationLocationId: "loc-demo-zaf",
      coverCategoryId: "cat-graa-essential",
      policyId: "policy-graa-2025-26",
      delta: 42,
      effectiveDate: new Date("2025-12-01T00:00:00.000Z"),
      note: "Opening baseline (demo)",
      kind: "BASELINE",
      createdByUserId: "user-insurer",
      createdAt: new Date("2025-12-01T00:00:00.000Z"),
    },
    {
      id: "end-demo-ken-baseline",
      clientId: "client-graa",
      organisationLocationId: "loc-demo-ken",
      coverCategoryId: "cat-graa-premium",
      policyId: "policy-graa-2025-26",
      delta: 18,
      effectiveDate: new Date("2025-12-01T00:00:00.000Z"),
      note: "Opening baseline (demo)",
      kind: "BASELINE",
      createdByUserId: "user-insurer",
      createdAt: new Date("2025-12-01T00:00:00.000Z"),
    },
    {
      id: "end-demo-zaf-add-mar",
      clientId: "client-graa",
      organisationLocationId: "loc-demo-zaf",
      coverCategoryId: "cat-graa-essential",
      policyId: "policy-graa-2025-26",
      delta: 5,
      effectiveDate: new Date("2026-03-15T00:00:00.000Z"),
      note: "Mid-term add (demo chart series)",
      kind: "ADD",
      createdByUserId: "user-insurer",
      createdAt: new Date("2026-03-15T00:00:00.000Z"),
    },
    {
      id: "end-demo-ken-remove-jun",
      clientId: "client-graa",
      organisationLocationId: "loc-demo-ken",
      coverCategoryId: "cat-graa-premium",
      policyId: "policy-graa-2025-26",
      delta: -2,
      effectiveDate: new Date("2026-06-01T00:00:00.000Z"),
      note: "Mid-term remove (demo chart series)",
      kind: "REMOVE",
      createdByUserId: "user-insurer",
      createdAt: new Date("2026-06-01T00:00:00.000Z"),
    },
  ],
};
